In [1]:
import pandas as pd
import numpy as np
import torch

In [2]:
df = pd.read_pickle("data/urfunny.pkl")
df

sentence  \
0      [finally in desperation they went and they con...   
1                they gave it back to the wise old woman   
2      [the most fundamental way in which the third s...   
3      and as the saying goes when angry you will mak...   
4             [i tried to remember to go to the balcony]   
...                                                  ...   
20327  so i found that they had a friend a local acco...   
20328  [so their scores had gone up from zero to perc...   
20329                              just say to them cool   
20330  [the worst in, they used everything that they ...   
20331  a single child in front of a single computer w...   

                                                features  \
0      [[finally, in, desperation, they, went, and, t...   
1      [they, gave, it, back, to, the, wise, old, woman]   
2      [[the, most, fundamental, way, in, which, the,...   
3      [and, as, the, saying, goes, when, angry, you,...   
4      [[i, tried, to, remember, to, go, to, the, bal...   
...                                                  ...   
20327  [so, i, found, that, they, had, a, friend, a, ...   
20328  [[so, their, scores, had, gone, up, from, zero...   
20329                        [just, say, to, them, cool]   
20330  [[the, worst, in], [they, used, everything, th...   
20331  [a, single, child, in, front, of, a, single, c...   

                                               intervals           timings  \
0      [[[0.0, 0.339], [0.339, 0.459], [0.459, 1.157]...  (24.933, 28.206)   
1      [[28.415, 28.475], [28.475, 28.565], [28.565, ...  (28.415, 29.273)   
2      [[[0.0, 0.06], [0.06, 0.299], [0.319, 1.427], ...   (21.92, 25.841)   
3      [[26.889, 27.039], [27.039, 27.188], [27.188, ...  (26.889, 29.772)   
4      [[[0.0, 0.18], [0.18, 0.499], [0.499, 0.559], ...      (0.0, 2.365)   
...                                                  ...               ...   
20327  [[56.142, 56.482], [56.482, 56.781], [56.881, ...   (56.142, 61.69)   
20328  [[[0.0, 0.359], [0.359, 0.489], [0.489, 0.878]...  (24.644, 30.062)   
20329  [[31.389, 31.558], [31.558, 31.708], [31.708, ...  (31.389, 32.177)   
20330  [[[0.0, 0.06], [0.06, 0.2], [0.409, 0.559]], [...  (33.354, 37.245)   
20331  [[38.004, 38.073], [38.073, 38.403], [38.403, ...  (38.004, 41.376)   

      split  file_id dialog   humour  context  \
0      test    11318   1017  CONTEXT     True   
1      test    11318   1017        1    False   
2      test    11319   1017  CONTEXT     True   
3      test    11319   1017        1    False   
4      test    11321   1017  CONTEXT     True   
...     ...      ...    ...      ...      ...   
20327   val    10945    949        0    False   
20328   val    10946    949  CONTEXT     True   
20329   val    10946    949        0    False   
20330   val    10948    949  CONTEXT     True   
20331   val    10948    949        0    False   

                                                timings2  ...  \
0      [(0.0, 4.37), (5.019, 12.252), (13.519, 14.717...  ...   
1                                       (28.415, 29.273)  ...   
2      [(0.0, 7.273), (8.022, 15.475), (16.233, 21.57...  ...   
3                                       (26.889, 29.772)  ...   
4                                         [(0.0, 2.365)]  ...   
...                                                  ...  ...   
20327                                    (56.142, 61.69)  ...   
20328  [(0.0, 5.777), (6.146, 6.824), (8.381, 13.928)...  ...   
20329                                   (31.389, 32.177)  ...   
20330  [(0.0, 0.559), (1.896, 5.927), (7.982, 11.963)...  ...   
20331                                   (38.004, 41.376)  ...   

                                audio_path  \
0      ../../data/urfunny2_audio/11318.wav   
1      ../../data/urfunny2_audio/11318.wav   
2      ../../data/urfunny2_audio/11319.wav   
3      ../../data/urfunny2_audio/11319.wav   
4      ../../data/urfunny2_audio/11321.wav   
...                    

In [4]:
type(df.iloc[1]['bbox'])

list

In [11]:
weights = torch.sort(
    torch.Tensor(
        list(
            dict(
                sorted(
                    (dict(1 / np.sqrt((df["emotion"].value_counts()))).items())
                )
            ).values()
        )
    )
).values
weights = weights / weights.sum()
weights

tensor([0.1293, 0.1345, 0.1673, 0.1688, 0.1723, 0.2279])

In [16]:
# in weights array swap 0 and 1


tensor([0.1345, 0.1293, 0.1688, 0.1673, 0.1723, 0.2279])

In [13]:
labels = df["emotion"].value_counts()
class_counts = torch.Tensor(
    list(dict(sorted((dict((labels)).items()))).values())
).to(int)
class_counts

tensor([1708, 1849, 1084, 1103, 1041,  595])

In [7]:
dict(sorted((dict(1 / np.sqrt((df["emotion"].value_counts()))).items()))).values()

dict_values([0.024196695924791362, 0.023255813953488372, 0.03037283696153935, 0.03011010318298389, 0.030993786368687184, 0.040996003084539386])

In [7]:
emotions = [
        "neutral",
        "frustration",
        "sadness",
        "anger",
        "excited",
        "happiness",
    ]
wanted_label2id = {emotion: idx for idx, emotion in enumerate(emotions)}
wanted_id2label = {val: key for key, val in wanted_label2id.items()}

In [8]:
wanted_label2id

{'neutral': 0,
 'frustration': 1,
 'sadness': 2,
 'anger': 3,
 'excited': 4,
 'happiness': 5}

In [16]:
wanted_id2label

{0: 'neutral',
 1: 'frustration',
 2: 'sadness',
 3: 'anger',
 4: 'excited',
 5: 'happiness'}

In [9]:
label2id = (
    df.drop_duplicates("emotion_label").set_index("emotion_label").to_dict()["emotion"]
)
id2label = {v: k for k, v in label2id.items()}

In [10]:
label2id

{'frustrated': 0, 'neutral': 1, 'angry': 2, 'happy': 5, 'sad': 3, 'excited': 4}

In [18]:
wanted_id2label  = {0: 'neutral',
 1: 'frustrated',
 2: 'sad',
 3: 'angry',
 4: 'excited',
 5: 'happy'}

In [12]:
curr2want_ids = {
 0: 1,
 1: 0,
 2: 3,
 3: 2,
 4: 4,
 5: 5
 }

In [13]:
df['emotion'].value_counts()

emotion
0    1849
1    1708
2    1103
3    1084
4    1041
5     595
Name: count, dtype: int64

In [14]:
# df['emotion_label'] = df['emotion_label']
df['emotion'] = df['emotion'].apply(lambda x: curr2want_ids[x])
df['emotion'].value_counts()

emotion
1    1849
0    1708
3    1103
2    1084
4    1041
5     595
Name: count, dtype: int64

In [15]:
df['emotion_label'].value_counts()

emotion_label
frustrated    1849
neutral       1708
angry         1103
sad           1084
excited       1041
happy          595
Name: count, dtype: int64

In [20]:
df['emotion_label'] = df['emotion'].apply(lambda x: wanted_id2label[x])
df['emotion_label'].value_counts()

emotion_label
frustrated    1849
neutral       1708
angry         1103
sad           1084
excited       1041
happy          595
Name: count, dtype: int64

In [22]:
df.to_pickle("data/iemo.pkl")

In [24]:
olddf = pd.read_pickle("data/iemo.pkl")
olddf

talker sentiment_label  dialog  \
0          MARY      frustrated       7   
1         JAMES         neutral       7   
2         JAMES         neutral       7   
3         JAMES         neutral       7   
4         JAMES         neutral       7   
...         ...             ...     ...   
7375    WILLIAM         excited     149   
7376    WILLIAM         excited     149   
7377    WILLIAM         excited     149   
7378    WILLIAM         excited     149   
7379  ELIZABETH         neutral     149   

                                        text_w_one_prev  sentiment  \
0                         MARY: What's he going to say?          0   
1     MARY: What's he going to say? </s></s> JAMES: ...          1   
2     JAMES: He saw it. </s></s> JAMES: He was out h...          1   
3     JAMES: He was out here when it broke. </s></s>...          1   
4     JAMES: Four o clock this morning.  I heard a c...          1   
...                                                 ...        ...   
7375  ELIZABETH: Oh, It burnt my comb and all the to...          4   
7376  WILLIAM: [LAUGHTER] That was quit a rouser, wa...          4   
7377  WILLIAM: Oh, I didn't hit you very hard. </s><...          4   
7378  WILLIAM: I should never forget his face. [LAUG...          4   
7379  WILLIAM: We were very much younger then. </s><...          1   

                 timings                                               bbox  \
0           (6.21, 9.32)  [[[65, 33, 200, 217]], [[63, 32, 203, 217]], [...   
1     (11.9892, 15.1219)  [[[24, 37, 172, 217], [0, 86, 36, 219], [182, ...   
2     (19.0456, 22.3962)  [[[19, 36, 175, 216], [2, 62, 54, 224], [182, ...   
3        (24.8, 35.9971)  [[[40, 37, 176, 217], [2, 74, 68, 220], [183, ...   
4         (38.66, 40.53)  [[[27, 35, 168, 218], [184, 129, 222, 205], [0...   
...                  ...                                                ...   
7375     (215.4, 220.75)  [[[61, 22, 188, 216]], [[60, 20, 187, 215]], [...   
7376    (221.13, 223.83)  [[[61, 16, 189, 216]], [[61, 15, 188, 216]], [...   
7377    (229.88, 233.06)  [[[57, 13, 190, 213]], [[56, 16, 190, 215]], [...   
7378    (234.14, 236.66)  [[[62, 11, 190, 215]], [[60, 13, 189, 214]], [...   
7379  (245.06, 247.0439)  [[[68, 65, 191, 219], [2, 155, 43, 218]], [[68...   

                                        audio_path  \
0     ../../data/iemocap_wav/Ses01F_script01_1.wav   
1     ../../data/iemocap_wav/Ses01F_script01_1.wav   
2     ../../data/iemocap_wav/Ses01F_script01_1.wav   
3     ../../data/iemocap_wav/Ses01F_script01_1.wav   
4     ../../data/iemocap_wav/Ses01F_script01_1.wav   
...                                            ...   
7375  ../../data/iemocap_wav/Ses05M_script03_1.wav   
7376  ../../data/iemocap_wav/Ses05M_script03_1.wav   
7377  ../../data/iemocap_wav/Ses05M_script03_1.wav   
7378  ../../data/iemocap_wav/Ses05M_script03_1.wav   
7379  ../../data/iemocap_wav/Ses05M_script03_1.wav   

                                        video_path  \
0     ../../data/iemocap_avi/Ses01F_script01_1.avi   
1     ../../data/iemocap_avi/Ses01F_script01_1.avi   
2     ../../data/iemocap_avi/Ses01F_script01_1.avi   
3     ../../data/iemocap_avi/Ses01F_script01_1.avi   
4     ../../data/iemocap_avi/Ses01F_script01_1.avi   
...                                            ...   
7375  ../../data/iemocap_avi/Ses05M_script03_1.avi   
7376  ../../data/iemocap_avi/Ses05M_script03_1.avi   
7377  ../../data/iemocap_avi/Ses05M_script03_1.avi   
7378  ../../data/iemocap_avi/Ses05M_script03_1.avi   
7379  ../../data/iemocap_avi/Ses05M_script03_1.avi   

                                                og_text  len  \
0                               What's he going to say?   16   
1                                            He saw it.   16   
2                        He was out here when it broke.   16   
3      Four o clock this morning.  I heard a crack a...   16   
4                                         I don't know.   16   
...                 

In [23]:
df

talker sentiment_label  dialog  \
0          MARY      frustrated       7   
1         JAMES         neutral       7   
2         JAMES         neutral       7   
3         JAMES         neutral       7   
4         JAMES         neutral       7   
...         ...             ...     ...   
7375    WILLIAM         excited     149   
7376    WILLIAM         excited     149   
7377    WILLIAM         excited     149   
7378    WILLIAM         excited     149   
7379  ELIZABETH         neutral     149   

                                        text_w_one_prev  sentiment  \
0                         MARY: What's he going to say?          0   
1     MARY: What's he going to say? </s></s> JAMES: ...          1   
2     JAMES: He saw it. </s></s> JAMES: He was out h...          1   
3     JAMES: He was out here when it broke. </s></s>...          1   
4     JAMES: Four o clock this morning.  I heard a c...          1   
...                                                 ...        ...   
7375  ELIZABETH: Oh, It burnt my comb and all the to...          4   
7376  WILLIAM: [LAUGHTER] That was quit a rouser, wa...          4   
7377  WILLIAM: Oh, I didn't hit you very hard. </s><...          4   
7378  WILLIAM: I should never forget his face. [LAUG...          4   
7379  WILLIAM: We were very much younger then. </s><...          1   

                 timings                                               bbox  \
0           (6.21, 9.32)  [[[65, 33, 200, 217]], [[63, 32, 203, 217]], [...   
1     (11.9892, 15.1219)  [[[24, 37, 172, 217], [0, 86, 36, 219], [182, ...   
2     (19.0456, 22.3962)  [[[19, 36, 175, 216], [2, 62, 54, 224], [182, ...   
3        (24.8, 35.9971)  [[[40, 37, 176, 217], [2, 74, 68, 220], [183, ...   
4         (38.66, 40.53)  [[[27, 35, 168, 218], [184, 129, 222, 205], [0...   
...                  ...                                                ...   
7375     (215.4, 220.75)  [[[61, 22, 188, 216]], [[60, 20, 187, 215]], [...   
7376    (221.13, 223.83)  [[[61, 16, 189, 216]], [[61, 15, 188, 216]], [...   
7377    (229.88, 233.06)  [[[57, 13, 190, 213]], [[56, 16, 190, 215]], [...   
7378    (234.14, 236.66)  [[[62, 11, 190, 215]], [[60, 13, 189, 214]], [...   
7379  (245.06, 247.0439)  [[[68, 65, 191, 219], [2, 155, 43, 218]], [[68...   

                                        audio_path  \
0     ../../data/iemocap_wav/Ses01F_script01_1.wav   
1     ../../data/iemocap_wav/Ses01F_script01_1.wav   
2     ../../data/iemocap_wav/Ses01F_script01_1.wav   
3     ../../data/iemocap_wav/Ses01F_script01_1.wav   
4     ../../data/iemocap_wav/Ses01F_script01_1.wav   
...                                            ...   
7375  ../../data/iemocap_wav/Ses05M_script03_1.wav   
7376  ../../data/iemocap_wav/Ses05M_script03_1.wav   
7377  ../../data/iemocap_wav/Ses05M_script03_1.wav   
7378  ../../data/iemocap_wav/Ses05M_script03_1.wav   
7379  ../../data/iemocap_wav/Ses05M_script03_1.wav   

                                        video_path  \
0     ../../data/iemocap_avi/Ses01F_script01_1.avi   
1     ../../data/iemocap_avi/Ses01F_script01_1.avi   
2     ../../data/iemocap_avi/Ses01F_script01_1.avi   
3     ../../data/iemocap_avi/Ses01F_script01_1.avi   
4     ../../data/iemocap_avi/Ses01F_script01_1.avi   
...                                            ...   
7375  ../../data/iemocap_avi/Ses05M_script03_1.avi   
7376  ../../data/iemocap_avi/Ses05M_script03_1.avi   
7377  ../../data/iemocap_avi/Ses05M_script03_1.avi   
7378  ../../data/iemocap_avi/Ses05M_script03_1.avi   
7379  ../../data/iemocap_avi/Ses05M_script03_1.avi   

                                                og_text  len  \
0                               What's he going to say?   16   
1                                            He saw it.   16   
2                        He was out here when it broke.   16   
3      Four o clock this morning.  I heard a crack a...   16   
4                                         I don't know.   16   
...                 

In [41]:
def process_intervals(intervals, limit = 4):
    # Initialize the running total and the limit
    # print(intervals , flush = True)
    if  len(intervals)  == 0:
        return (0 , 500)    
    if isinstance(intervals[0][0] , list) or isinstance(intervals[0][0] , np.ndarray):
        
        running_total = 0

        # Initialize the list to store the intervals that fit within the limit
        limited_intervals = []

        # Go through the intervals in reverse order
        for idx_i , i in enumerate(reversed(range(len(intervals)))):
            sublist = intervals[i]
            for j , interval in enumerate(reversed(sublist)):
                # Calculate the absolute difference between end and start
                time_diff = abs(interval[1] - interval[0])
                # If adding this time difference to the running total would make it greater than the limit
                if running_total + time_diff > limit and idx_i == 0 and j == 0:
                    # if on the first iteration the first interval is already greater than the limit
                    limited_intervals.append(interval)
                    break
                elif running_total + time_diff > limit:
                    # Stop the loop
                    break
                
                # Add the time difference to the running total
                running_total += time_diff
                
                # Add the interval to the list
                limited_intervals.append(interval)
            
            # If we haven't reached the limit yet, add the gap to the next sublist (if there is one)
            if i > 0 and running_total < limit:
                gap = intervals[i][0][0] - intervals[i-1][-1][1]
                running_total += gap

        # Reverse the list of intervals to get them in the original order
        limited_intervals = list(reversed(limited_intervals))

        return (limited_intervals[0][0], limited_intervals[-1][1])
    else:
        return (intervals[0][0], intervals[-1][1])

In [42]:
from tqdm import tqdm
tqdm.pandas()

df['timings']  = df['intervals'].progress_apply( lambda x: process_intervals(x , limit = 4))
df['video_timings']  = df['intervals'].progress_apply( lambda x: process_intervals(x , limit = 4))
df['audio_timings']  = df['intervals'].progress_apply( lambda x: process_intervals(x , limit = 29))
df

  0%|          | 0/20332 [00:00<?, ?it/s]

100%|██████████| 20332/20332 [00:00<00:00, 102706.80it/s]


sentence  \
0      [finally in desperation they went and they con...   
1                they gave it back to the wise old woman   
2      [the most fundamental way in which the third s...   
3      and as the saying goes when angry you will mak...   
4             [i tried to remember to go to the balcony]   
...                                                  ...   
20327  so i found that they had a friend a local acco...   
20328  [so their scores had gone up from zero to perc...   
20329                              just say to them cool   
20330  [the worst in, they used everything that they ...   
20331  a single child in front of a single computer w...   

                                                features  \
0      [[finally, in, desperation, they, went, and, t...   
1      [they, gave, it, back, to, the, wise, old, woman]   
2      [[the, most, fundamental, way, in, which, the,...   
3      [and, as, the, saying, goes, when, angry, you,...   
4      [[i, tried, to, remember, to, go, to, the, bal...   
...                                                  ...   
20327  [so, i, found, that, they, had, a, friend, a, ...   
20328  [[so, their, scores, had, gone, up, from, zero...   
20329                        [just, say, to, them, cool]   
20330  [[the, worst, in], [they, used, everything, th...   
20331  [a, single, child, in, front, of, a, single, c...   

                                               intervals           timings  \
0      [[[0.0, 0.339], [0.339, 0.459], [0.459, 1.157]...  (24.933, 28.206)   
1      [[28.415, 28.475], [28.475, 28.565], [28.565, ...  (28.415, 29.273)   
2      [[[0.0, 0.06], [0.06, 0.299], [0.319, 1.427], ...   (21.92, 25.841)   
3      [[26.889, 27.039], [27.039, 27.188], [27.188, ...  (26.889, 29.772)   
4      [[[0.0, 0.18], [0.18, 0.499], [0.499, 0.559], ...      (0.0, 2.365)   
...                                                  ...               ...   
20327  [[56.142, 56.482], [56.482, 56.781], [56.881, ...   (56.142, 61.69)   
20328  [[[0.0, 0.359], [0.359, 0.489], [0.489, 0.878]...  (24.644, 30.062)   
20329  [[31.389, 31.558], [31.558, 31.708], [31.708, ...  (31.389, 32.177)   
20330  [[[0.0, 0.06], [0.06, 0.2], [0.409, 0.559]], [...  (33.354, 37.245)   
20331  [[38.004, 38.073], [38.073, 38.403], [38.403, ...  (38.004, 41.376)   

      split  file_id  root    label  context  \
0      test    11318  1017  CONTEXT     True   
1      test    11318  1017        1    False   
2      test    11319  1017  CONTEXT     True   
3      test    11319  1017        1    False   
4      test    11321  1017  CONTEXT     True   
...     ...      ...   ...      ...      ...   
20327   val    10945   949        0    False   
20328   val    10946   949  CONTEXT     True   
20329   val    10946   949        0    False   
20330   val    10948   949  CONTEXT     True   
20331   val    10948   949        0    False   

                                                timings2  proc_intervals_4  \
0      [(0.0, 4.37), (5.019, 12.252), (13.519, 14.717...  (21.022, 28.206)   
1                                       (28.415, 29.273)  (28.415, 29.273)   
2      [(0.0, 7.273), (8.022, 15.475), (16.233, 21.57...   (21.92, 25.841)   
3                                       (26.889, 29.772)  (26.889, 29.772)   
4                                         [(0.0, 2.365)]      (0.0, 2.365)   
...                                                  ...               ...   
20327                                    (56.142, 61.69)   (56.142, 61.69)   
20328  [(0.0, 5.777), (6.146, 6.824), (8.381, 13.928)...  (24.644, 30.062)   
20329                                   (31.389, 32.177)  (31.389, 32.177)   
20330  [(0.0, 0.559), (1.896, 5.927), (7.982, 11.963)...  (11.903, 37.245)   
20331                                   (38.004, 41.376)  (38.004, 41.376)   

                                audio_path  \
0      ../../data/urfunny2_audio/11318.wav   
1      ../../data/urfunny2_audio/11318.wav   
2      ../../data

In [43]:
df.to_pickle("data/urfunny.pkl")

True

In [44]:
df['absolute'] = df['audio_timings'].apply(lambda x: x[1] - x[0])


In [5]:
jdx = 6
df['intervals'].iloc[jdx] , df['audio_timings'].iloc[jdx] , df['video_timings'].iloc[jdx] , df['absolute'] .iloc[jdx]

(array([[[0.   , 0.11 ],
         [0.11 , 0.399],
         [0.399, 0.729],
         [0.729, 0.968],
         [1.068, 1.417]],
 
        [[1.627, 1.686],
         [1.686, 1.876],
         [1.876, 2.165],
         [2.165, 2.345],
         [2.345, 3.003]]]),
 (array([0.  , 0.11]), array([1.686, 1.876])),
 (array([0.  , 0.11]), array([1.686, 1.876])),
 array([1.686, 1.766]))

In [9]:
df[ len(df['absolute'])  == 1 ]

KeyError: False

In [24]:
df[df['absolute'].apply(lambda x: not isinstance(x, int))]

sentence  \
0      [finally in desperation they went and they con...   
1                they gave it back to the wise old woman   
2      [the most fundamental way in which the third s...   
3      and as the saying goes when angry you will mak...   
4             [i tried to remember to go to the balcony]   
...                                                  ...   
20327  so i found that they had a friend a local acco...   
20328  [so their scores had gone up from zero to perc...   
20329                              just say to them cool   
20330  [the worst in, they used everything that they ...   
20331  a single child in front of a single computer w...   

                                                features  \
0      [[finally, in, desperation, they, went, and, t...   
1      [they, gave, it, back, to, the, wise, old, woman]   
2      [[the, most, fundamental, way, in, which, the,...   
3      [and, as, the, saying, goes, when, angry, you,...   
4      [[i, tried, to, remember, to, go, to, the, bal...   
...                                                  ...   
20327  [so, i, found, that, they, had, a, friend, a, ...   
20328  [[so, their, scores, had, gone, up, from, zero...   
20329                        [just, say, to, them, cool]   
20330  [[the, worst, in], [they, used, everything, th...   
20331  [a, single, child, in, front, of, a, single, c...   

                                               intervals           timings  \
0      [[[0.0, 0.339], [0.339, 0.459], [0.459, 1.157]...  (24.933, 28.206)   
1      [[28.415, 28.475], [28.475, 28.565], [28.565, ...  (28.415, 29.273)   
2      [[[0.0, 0.06], [0.06, 0.299], [0.319, 1.427], ...   (21.92, 25.841)   
3      [[26.889, 27.039], [27.039, 27.188], [27.188, ...  (26.889, 29.772)   
4      [[[0.0, 0.18], [0.18, 0.499], [0.499, 0.559], ...      (0.0, 2.365)   
...                                                  ...               ...   
20327  [[56.142, 56.482], [56.482, 56.781], [56.881, ...   (56.142, 61.69)   
20328  [[[0.0, 0.359], [0.359, 0.489], [0.489, 0.878]...  (24.644, 30.062)   
20329  [[31.389, 31.558], [31.558, 31.708], [31.708, ...  (31.389, 32.177)   
20330  [[[0.0, 0.06], [0.06, 0.2], [0.409, 0.559]], [...  (33.354, 37.245)   
20331  [[38.004, 38.073], [38.073, 38.403], [38.403, ...  (38.004, 41.376)   

      split  file_id  root    label  context  \
0      test    11318  1017  CONTEXT     True   
1      test    11318  1017        1    False   
2      test    11319  1017  CONTEXT     True   
3      test    11319  1017        1    False   
4      test    11321  1017  CONTEXT     True   
...     ...      ...   ...      ...      ...   
20327   val    10945   949        0    False   
20328   val    10946   949  CONTEXT     True   
20329   val    10946   949        0    False   
20330   val    10948   949  CONTEXT     True   
20331   val    10948   949        0    False   

                                                timings2  proc_intervals_4  \
0      [(0.0, 4.37), (5.019, 12.252), (13.519, 14.717...  (21.022, 28.206)   
1                                       (28.415, 29.273)  (28.415, 29.273)   
2      [(0.0, 7.273), (8.022, 15.475), (16.233, 21.57...   (21.92, 25.841)   
3                                       (26.889, 29.772)  (26.889, 29.772)   
4                                         [(0.0, 2.365)]      (0.0, 2.365)   
...                                                  ...               ...   
20327                                    (56.142, 61.69)   (56.142, 61.69)   
20328  [(0.0, 5.777), (6.146, 6.824), (8.381, 13.928)...  (24.644, 30.062)   
20329                                   (31.389, 32.177)  (31.389, 32.177)   
20330  [(0.0, 0.559), (1.896, 5.927), (7.982, 11.963)...  (11.903, 37.245)   
20331                                   (38.004, 41.376)  (38.004, 41.376)   

                                audio_path  \
0      ../../data/urfunny2_audio/11318.wav   
1      ../../data/urfunny2_audio/11318.wav   
2      ../../data

(53.548, 56.821)

In [ ]:
isinstance(a[0][0] , list)

In [ ]:
process_intervals(df['intervals'].iloc[1])