In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_pickle("data/urfunny.pkl")
df

sentence  \
0      [finally in desperation they went and they con...   
1                they gave it back to the wise old woman   
2      [the most fundamental way in which the third s...   
3      and as the saying goes when angry you will mak...   
4             [i tried to remember to go to the balcony]   
...                                                  ...   
20327  so i found that they had a friend a local acco...   
20328  [so their scores had gone up from zero to perc...   
20329                              just say to them cool   
20330  [the worst in, they used everything that they ...   
20331  a single child in front of a single computer w...   

                                                features  \
0      [[finally, in, desperation, they, went, and, t...   
1      [they, gave, it, back, to, the, wise, old, woman]   
2      [[the, most, fundamental, way, in, which, the,...   
3      [and, as, the, saying, goes, when, angry, you,...   
4      [[i, tried, to, remember, to, go, to, the, bal...   
...                                                  ...   
20327  [so, i, found, that, they, had, a, friend, a, ...   
20328  [[so, their, scores, had, gone, up, from, zero...   
20329                        [just, say, to, them, cool]   
20330  [[the, worst, in], [they, used, everything, th...   
20331  [a, single, child, in, front, of, a, single, c...   

                                               intervals           timings  \
0      [[[0.0, 0.339], [0.339, 0.459], [0.459, 1.157]...  (24.933, 28.206)   
1      [[28.415, 28.475], [28.475, 28.565], [28.565, ...  (28.415, 29.273)   
2      [[[0.0, 0.06], [0.06, 0.299], [0.319, 1.427], ...   (21.92, 25.841)   
3      [[26.889, 27.039], [27.039, 27.188], [27.188, ...  (26.889, 29.772)   
4      [[[0.0, 0.18], [0.18, 0.499], [0.499, 0.559], ...      (0.0, 2.365)   
...                                                  ...               ...   
20327  [[56.142, 56.482], [56.482, 56.781], [56.881, ...   (56.142, 61.69)   
20328  [[[0.0, 0.359], [0.359, 0.489], [0.489, 0.878]...  (24.644, 30.062)   
20329  [[31.389, 31.558], [31.558, 31.708], [31.708, ...  (31.389, 32.177)   
20330  [[[0.0, 0.06], [0.06, 0.2], [0.409, 0.559]], [...  (33.354, 37.245)   
20331  [[38.004, 38.073], [38.073, 38.403], [38.403, ...  (38.004, 41.376)   

      split  file_id  root    label  context  \
0      test    11318  1017  CONTEXT     True   
1      test    11318  1017        1    False   
2      test    11319  1017  CONTEXT     True   
3      test    11319  1017        1    False   
4      test    11321  1017  CONTEXT     True   
...     ...      ...   ...      ...      ...   
20327   val    10945   949        0    False   
20328   val    10946   949  CONTEXT     True   
20329   val    10946   949        0    False   
20330   val    10948   949  CONTEXT     True   
20331   val    10948   949        0    False   

                                                timings2  proc_intervals_4  \
0      [(0.0, 4.37), (5.019, 12.252), (13.519, 14.717...  (21.022, 28.206)   
1                                       (28.415, 29.273)  (28.415, 29.273)   
2      [(0.0, 7.273), (8.022, 15.475), (16.233, 21.57...   (21.92, 25.841)   
3                                       (26.889, 29.772)  (26.889, 29.772)   
4                                         [(0.0, 2.365)]      (0.0, 2.365)   
...                                                  ...               ...   
20327                                    (56.142, 61.69)   (56.142, 61.69)   
20328  [(0.0, 5.777), (6.146, 6.824), (8.381, 13.928)...  (24.644, 30.062)   
20329                                   (31.389, 32.177)  (31.389, 32.177)   
20330  [(0.0, 0.559), (1.896, 5.927), (7.982, 11.963)...  (11.903, 37.245)   
20331                                   (38.004, 41.376)  (38.004, 41.376)   

                                audio_path  \
0      ../../data/urfunny2_audio/11318.wav   
1      ../../data/urfunny2_audio/11318.wav   
2      ../../data

In [41]:
def process_intervals(intervals, limit = 4):
    # Initialize the running total and the limit
    # print(intervals , flush = True)
    if  len(intervals)  == 0:
        return (0 , 500)    
    if isinstance(intervals[0][0] , list) or isinstance(intervals[0][0] , np.ndarray):
        
        running_total = 0

        # Initialize the list to store the intervals that fit within the limit
        limited_intervals = []

        # Go through the intervals in reverse order
        for idx_i , i in enumerate(reversed(range(len(intervals)))):
            sublist = intervals[i]
            for j , interval in enumerate(reversed(sublist)):
                # Calculate the absolute difference between end and start
                time_diff = abs(interval[1] - interval[0])
                # If adding this time difference to the running total would make it greater than the limit
                if running_total + time_diff > limit and idx_i == 0 and j == 0:
                    # if on the first iteration the first interval is already greater than the limit
                    limited_intervals.append(interval)
                    break
                elif running_total + time_diff > limit:
                    # Stop the loop
                    break
                
                # Add the time difference to the running total
                running_total += time_diff
                
                # Add the interval to the list
                limited_intervals.append(interval)
            
            # If we haven't reached the limit yet, add the gap to the next sublist (if there is one)
            if i > 0 and running_total < limit:
                gap = intervals[i][0][0] - intervals[i-1][-1][1]
                running_total += gap

        # Reverse the list of intervals to get them in the original order
        limited_intervals = list(reversed(limited_intervals))

        return (limited_intervals[0][0], limited_intervals[-1][1])
    else:
        return (intervals[0][0], intervals[-1][1])

In [42]:
from tqdm import tqdm
tqdm.pandas()

df['timings']  = df['intervals'].progress_apply( lambda x: process_intervals(x , limit = 4))
df['video_timings']  = df['intervals'].progress_apply( lambda x: process_intervals(x , limit = 4))
df['audio_timings']  = df['intervals'].progress_apply( lambda x: process_intervals(x , limit = 29))
df

  0%|          | 0/20332 [00:00<?, ?it/s]

100%|██████████| 20332/20332 [00:00<00:00, 102706.80it/s]


sentence  \
0      [finally in desperation they went and they con...   
1                they gave it back to the wise old woman   
2      [the most fundamental way in which the third s...   
3      and as the saying goes when angry you will mak...   
4             [i tried to remember to go to the balcony]   
...                                                  ...   
20327  so i found that they had a friend a local acco...   
20328  [so their scores had gone up from zero to perc...   
20329                              just say to them cool   
20330  [the worst in, they used everything that they ...   
20331  a single child in front of a single computer w...   

                                                features  \
0      [[finally, in, desperation, they, went, and, t...   
1      [they, gave, it, back, to, the, wise, old, woman]   
2      [[the, most, fundamental, way, in, which, the,...   
3      [and, as, the, saying, goes, when, angry, you,...   
4      [[i, tried, to, remember, to, go, to, the, bal...   
...                                                  ...   
20327  [so, i, found, that, they, had, a, friend, a, ...   
20328  [[so, their, scores, had, gone, up, from, zero...   
20329                        [just, say, to, them, cool]   
20330  [[the, worst, in], [they, used, everything, th...   
20331  [a, single, child, in, front, of, a, single, c...   

                                               intervals           timings  \
0      [[[0.0, 0.339], [0.339, 0.459], [0.459, 1.157]...  (24.933, 28.206)   
1      [[28.415, 28.475], [28.475, 28.565], [28.565, ...  (28.415, 29.273)   
2      [[[0.0, 0.06], [0.06, 0.299], [0.319, 1.427], ...   (21.92, 25.841)   
3      [[26.889, 27.039], [27.039, 27.188], [27.188, ...  (26.889, 29.772)   
4      [[[0.0, 0.18], [0.18, 0.499], [0.499, 0.559], ...      (0.0, 2.365)   
...                                                  ...               ...   
20327  [[56.142, 56.482], [56.482, 56.781], [56.881, ...   (56.142, 61.69)   
20328  [[[0.0, 0.359], [0.359, 0.489], [0.489, 0.878]...  (24.644, 30.062)   
20329  [[31.389, 31.558], [31.558, 31.708], [31.708, ...  (31.389, 32.177)   
20330  [[[0.0, 0.06], [0.06, 0.2], [0.409, 0.559]], [...  (33.354, 37.245)   
20331  [[38.004, 38.073], [38.073, 38.403], [38.403, ...  (38.004, 41.376)   

      split  file_id  root    label  context  \
0      test    11318  1017  CONTEXT     True   
1      test    11318  1017        1    False   
2      test    11319  1017  CONTEXT     True   
3      test    11319  1017        1    False   
4      test    11321  1017  CONTEXT     True   
...     ...      ...   ...      ...      ...   
20327   val    10945   949        0    False   
20328   val    10946   949  CONTEXT     True   
20329   val    10946   949        0    False   
20330   val    10948   949  CONTEXT     True   
20331   val    10948   949        0    False   

                                                timings2  proc_intervals_4  \
0      [(0.0, 4.37), (5.019, 12.252), (13.519, 14.717...  (21.022, 28.206)   
1                                       (28.415, 29.273)  (28.415, 29.273)   
2      [(0.0, 7.273), (8.022, 15.475), (16.233, 21.57...   (21.92, 25.841)   
3                                       (26.889, 29.772)  (26.889, 29.772)   
4                                         [(0.0, 2.365)]      (0.0, 2.365)   
...                                                  ...               ...   
20327                                    (56.142, 61.69)   (56.142, 61.69)   
20328  [(0.0, 5.777), (6.146, 6.824), (8.381, 13.928)...  (24.644, 30.062)   
20329                                   (31.389, 32.177)  (31.389, 32.177)   
20330  [(0.0, 0.559), (1.896, 5.927), (7.982, 11.963)...  (11.903, 37.245)   
20331                                   (38.004, 41.376)  (38.004, 41.376)   

                                audio_path  \
0      ../../data/urfunny2_audio/11318.wav   
1      ../../data/urfunny2_audio/11318.wav   
2      ../../data

In [43]:
df.to_pickle("data/urfunny.pkl")

True

In [44]:
df['absolute'] = df['audio_timings'].apply(lambda x: x[1] - x[0])


In [5]:
jdx = 6
df['intervals'].iloc[jdx] , df['audio_timings'].iloc[jdx] , df['video_timings'].iloc[jdx] , df['absolute'] .iloc[jdx]

(array([[[0.   , 0.11 ],
         [0.11 , 0.399],
         [0.399, 0.729],
         [0.729, 0.968],
         [1.068, 1.417]],
 
        [[1.627, 1.686],
         [1.686, 1.876],
         [1.876, 2.165],
         [2.165, 2.345],
         [2.345, 3.003]]]),
 (array([0.  , 0.11]), array([1.686, 1.876])),
 (array([0.  , 0.11]), array([1.686, 1.876])),
 array([1.686, 1.766]))

In [9]:
df[ len(df['absolute'])  == 1 ]

KeyError: False

In [24]:
df[df['absolute'].apply(lambda x: not isinstance(x, int))]

sentence  \
0      [finally in desperation they went and they con...   
1                they gave it back to the wise old woman   
2      [the most fundamental way in which the third s...   
3      and as the saying goes when angry you will mak...   
4             [i tried to remember to go to the balcony]   
...                                                  ...   
20327  so i found that they had a friend a local acco...   
20328  [so their scores had gone up from zero to perc...   
20329                              just say to them cool   
20330  [the worst in, they used everything that they ...   
20331  a single child in front of a single computer w...   

                                                features  \
0      [[finally, in, desperation, they, went, and, t...   
1      [they, gave, it, back, to, the, wise, old, woman]   
2      [[the, most, fundamental, way, in, which, the,...   
3      [and, as, the, saying, goes, when, angry, you,...   
4      [[i, tried, to, remember, to, go, to, the, bal...   
...                                                  ...   
20327  [so, i, found, that, they, had, a, friend, a, ...   
20328  [[so, their, scores, had, gone, up, from, zero...   
20329                        [just, say, to, them, cool]   
20330  [[the, worst, in], [they, used, everything, th...   
20331  [a, single, child, in, front, of, a, single, c...   

                                               intervals           timings  \
0      [[[0.0, 0.339], [0.339, 0.459], [0.459, 1.157]...  (24.933, 28.206)   
1      [[28.415, 28.475], [28.475, 28.565], [28.565, ...  (28.415, 29.273)   
2      [[[0.0, 0.06], [0.06, 0.299], [0.319, 1.427], ...   (21.92, 25.841)   
3      [[26.889, 27.039], [27.039, 27.188], [27.188, ...  (26.889, 29.772)   
4      [[[0.0, 0.18], [0.18, 0.499], [0.499, 0.559], ...      (0.0, 2.365)   
...                                                  ...               ...   
20327  [[56.142, 56.482], [56.482, 56.781], [56.881, ...   (56.142, 61.69)   
20328  [[[0.0, 0.359], [0.359, 0.489], [0.489, 0.878]...  (24.644, 30.062)   
20329  [[31.389, 31.558], [31.558, 31.708], [31.708, ...  (31.389, 32.177)   
20330  [[[0.0, 0.06], [0.06, 0.2], [0.409, 0.559]], [...  (33.354, 37.245)   
20331  [[38.004, 38.073], [38.073, 38.403], [38.403, ...  (38.004, 41.376)   

      split  file_id  root    label  context  \
0      test    11318  1017  CONTEXT     True   
1      test    11318  1017        1    False   
2      test    11319  1017  CONTEXT     True   
3      test    11319  1017        1    False   
4      test    11321  1017  CONTEXT     True   
...     ...      ...   ...      ...      ...   
20327   val    10945   949        0    False   
20328   val    10946   949  CONTEXT     True   
20329   val    10946   949        0    False   
20330   val    10948   949  CONTEXT     True   
20331   val    10948   949        0    False   

                                                timings2  proc_intervals_4  \
0      [(0.0, 4.37), (5.019, 12.252), (13.519, 14.717...  (21.022, 28.206)   
1                                       (28.415, 29.273)  (28.415, 29.273)   
2      [(0.0, 7.273), (8.022, 15.475), (16.233, 21.57...   (21.92, 25.841)   
3                                       (26.889, 29.772)  (26.889, 29.772)   
4                                         [(0.0, 2.365)]      (0.0, 2.365)   
...                                                  ...               ...   
20327                                    (56.142, 61.69)   (56.142, 61.69)   
20328  [(0.0, 5.777), (6.146, 6.824), (8.381, 13.928)...  (24.644, 30.062)   
20329                                   (31.389, 32.177)  (31.389, 32.177)   
20330  [(0.0, 0.559), (1.896, 5.927), (7.982, 11.963)...  (11.903, 37.245)   
20331                                   (38.004, 41.376)  (38.004, 41.376)   

                                audio_path  \
0      ../../data/urfunny2_audio/11318.wav   
1      ../../data/urfunny2_audio/11318.wav   
2      ../../data

(53.548, 56.821)

In [ ]:
isinstance(a[0][0] , list)

In [ ]:
process_intervals(df['intervals'].iloc[1])